- InstanceFleetType: MASTER
  InstanceTypeConfigs:
  - EbsConfiguration:
      EbsBlockDeviceConfigs:
      - VolumeSpecification: {SizeInGB: 50, VolumeType: gp2}
        VolumesPerInstance: 1
      EbsOptimized: false
    InstanceType: m1.large
    WeightedCapacity: 1
  Name: Master
  TargetOnDemandCapacity: 1
  TargetSpotCapacity: 0
- InstanceFleetType: CORE
  InstanceTypeConfigs:
  - EbsConfiguration:
      EbsBlockDeviceConfigs:
      - VolumeSpecification: {SizeInGB: 50, VolumeType: gp2}
        VolumesPerInstance: 1
      EbsOptimized: false
    InstanceType: m1.medium
    WeightedCapacity: 1
  - EbsConfiguration:
      EbsBlockDeviceConfigs:
      - VolumeSpecification: {SizeInGB: 100, VolumeType: gp2}
        VolumesPerInstance: 1
      EbsOptimized: false
    InstanceType: m1.large
    WeightedCapacity: 1
  Name: Core
  TargetOnDemandCapacity: 2
  TargetSpotCapacity: 0